theme: jekyll-theme-minimal
title: Chakri's homepage
description:If interested, you can read my dissertation here \hyperlink{https://refubium.fu-berlin.de/handle/fub188/42994}

remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
